# orc sprite defintion

[image]
tile_width = 64
tile_height = 64
filename = "assets/sprites/orc.png"

[[animation]]
# 0,0 - 7 frames
name = "stand_back"
frames = [0,1,2,3,4,5,6]
duration = 1.0

[[animation]]
# 0,1 - 7 frames
name = "stand_front_left"
frames = [13,14,15,16,17,18,19]
duration = 1.0

[[animation]]
# 0,2 - 7 frames
name = "stand_front"
frames = [26,27,28,29,30,31,32]
duration = 1.0

[[animation]]
# 0,3 - 7 frames
name = "stand_front_right"
frames = [39,40,41,42,43,44,45]
duration = 1.0

[[animation]]
# 0,4 - 8 frames
name = "attack_back"
frames = [52,53,54,55,56,57,58,59]
duration = 1.0

[[animation]]
# 0,5 - 8 frames
name = "attack_front_left"
frames = [65,66,67,68,69,70,71,72]
duration = 1.0

[[animation]]
# 0,6 - 8 frames
name = "attack_front"
frames = [78,79,80,81,82,83,84,85]
duration = 1.0

[[animation]]
# 0,7 - 8 frames
name = "attack_front_right"
frames = [91,92,93,94,95,96,97,98]
duration = 1.0

[[animation]]
# 0,8 - 6 frames
name = "walk_back"
frames = [104,105,106,107,108,109]
duration = 1.0

[[animation]]
# 0,9 - 6 frames
name = "walk_front_left"
frames = [117,118,119,120,121,122]
duration = 1.0

[[animation]]
# 0,10 - 6 frames
name = "walk_front"
frames = [130,131,132,133,134,135]
duration = 1.0

[[animation]]
# 0,11 - 6 frames
name = "walk_front_right"
frames = [143,144,145,146,147,148]
duration = 1.0

[[animation]]
# 0,12 - 6 frames
name = "punch_back"
frames = [156,157,158,159,160,161]
duration = 1.0

[[animation]]
# 0,13 - 6 frames
name = "punch_front_left"
frames = [169,170,171,172,173,174]
duration = 1.0

[[animation]]
# 0,14 - 6 frames
name = "punch_front"
frames = [182,183,184,185,186,187]
duration = 1.0

[[animation]]
# 0,15 - 6 frames
name = "punch_front_right"
frames = [195,196,197,198,199,200]
duration = 1.0

[[animation]]
# 0,16 - 13 frames
name = "idle_back"
frames = [208,209,210,211,212,213,214,215,216,217,218,219,220]
duration = 1.0

[[animation]]
# 0,17 - 13 frames
name = "idle_front_left"
frames = [221,222,223,224,225,226,227,228,229,230,231,232,233]
duration = 1.0

[[animation]]
# 0,18 - 13 frames
name = "idle_front"
frames = [234,235,236,237,238,239,240,241,242,243,244,245,246]
duration = 1.0

[[animation]]
# 0,19 - 13 frames
name = "idle_front_right"
frames = [247,248,249,250,251,252,253,254,255,256,257,258,259]
duration = 1.0

[[animation]]
# 0,20 - 6 frames
name = "roll"
frames = [260,261,262,263,264,265]
duration = 1.0
